DriveSec/Controllers/DriveSecController.cs
using DriveSec.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using System;
using System.IO;
using System.Threading.Tasks;
using YandexDisk.Client.Clients;
using YandexDisk.Client.Http;
using YandexDisk.Client.Protocol;
using QRCoder;

namespace DriveSec.Controllers
{
    public class DriveSecController : Controller
    {
        private readonly DriveSecContext _context;

        public DriveSecController(DriveSecContext context)
        {
            _context = context;
        }

        public class ChosenViewModel
        {
            public string login { get; set; }
            public string password { get; set; }
        }

        private readonly string _key = "";//Введите свой ключ к API
        private static readonly string _pathstandart = "disk:/DriveSec";
        private static readonly int _userid = 1; // пока тут 1, позже будет обычный userid
        private static string _path;
        private static int _actualFolderId;
        static DriveSecController()
        {
            _path = _pathstandart + "/" + _userid;
        }

        public IActionResult Index()
        {
            try
            {
                // Получение данных о пользователях
                var usersData = _context.Users.Select(c => new ChosenViewModel
                {
                    login = c.Login,
                    password = c.Password
                }).ToList();

                if (usersData != null)
                {
                    ViewData["SuccessMessage"] = "Все гуд!";
                    ViewData["UsersData"] = usersData;
                }
                else
                {
                    ViewData["ErrorMessage"] = "Все не гуд!";
                }

                _path = _pathstandart + "/" + _userid;
                _actualFolderId = _userid;
                // Получение списка файлов в папке с ID = 1
                var filesInFolder = _context.Files
                    .Where(file => file.FolderId == _userid)
                    .ToList();

                // Получение списка папок в папке с ID = 1
                var foldersInFolder = _context.Folders.Where(d => d.FolderWay == _path)
                    .ToList();

                return View((filesInFolder, foldersInFolder));
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = $"Ошибка: {ex.Message}";
                return View();
            }
        }

        public IActionResult OpenFolder(string folderName)
        {
            Console.WriteLine(folderName);
            try
            {
                // Получение данных о пользователях
                var usersData = _context.Users.Select(c => new ChosenViewModel
                {
                    login = _context.Users.Select(a => a.Login).FirstOrDefault(),
                    password = _context.Users.Select(a => a.Password).FirstOrDefault()
                }).ToList();

                int folderId = _context.Folders
                    .Where(d => d.FolderName == folderName && d.FolderWay == _path)
                    .Select(s => s.FolderId)
                    .FirstOrDefault();
                
                var filesInFolder = _context.Files
                    .Where(file => file.FolderId == folderId)
                    .ToList();

                _path += "/" + folderName;
                _actualFolderId = folderId;

                // Получение списка папок в папке
                var foldersInFolder = _context.Folders.Where(d => d.FolderWay == _path)
                    .ToList();

                return View("Index", (filesInFolder, foldersInFolder));
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = $"Ошибка: {ex.Message}";
                return View();
            }
        }

        [HttpPost]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> UploadFile(IFormFile file, string description, string selectedUsers)
        {
            if (file == null || file.Length <= 0)
            {
                return BadRequest("Не выбран файл для загрузки");
            }
            try
            {

                var api = new DiskHttpApi(_key);

                // Подготовка пути на диске для сохранения файла
                //var filePath = Path.Combine(_path, file.FileName);
                var filePath = (_path + "/" + file.FileName);

                // Получение ссылки для загрузки файла на Яндекс Диск
                var uploadLink = await api.Files.GetUploadLinkAsync(filePath, overwrite: true);
                
                // Загрузка файла на Яндекс Диск
                using (var stream = file.OpenReadStream())
                {
                    await api.Files.UploadAsync(uploadLink, stream);
                }

                //Выгрузка инфы в БД
                UploadFileDB(file.FileName, false, "", _actualFolderId);

                if (_actualFolderId==1)
                {
                    return RedirectToAction("Index", new { successMessage = "Файл успешно загружен на Яндекс Диск" });
                }
                else
                {
                    string folderName = _context.Folders
                        .Where(f => f.FolderId == _actualFolderId)
                        .Select(s => s.FolderName)
                        .FirstOrDefault();
                    string helpPath = "/" + folderName;
                    if (_path.EndsWith(helpPath))
                    {
                        _path = _path.Substring(0, _path.Length - helpPath.Length);
                    }
                    return RedirectToAction(nameof(OpenFolder), new {folderName});
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Возникла ошибка при загрузке файла: {ex.Message}");
            }
        }

        protected void UploadFileDB(string fileName, bool virusAvailiability, string virusDescrition, int folderId)
        {
            var newFile = new Models.File
            {
                FileName = fileName,
                CreationDate = DateTime.Now,
                VirusAvailiability = virusAvailiability,
                VirusDescription = virusDescrition,
                UploaderId = 1, //Потом будем получать id авторизованного 
                FolderId = folderId
            };
            _context.Files.Add(newFile);
            _context.SaveChanges();
            return;
        }

        [HttpPost]
        public async Task<IActionResult> CreateFolder(string folderName)
        {
            if (string.IsNullOrEmpty(folderName))
            {
                return BadRequest("Имя папки не может быть пустым");
            }

            try
            {
                var api = new DiskHttpApi(_key);

                // Подготовка пути на диске для создания папки
                var folderPath = _path + "/" + folderName;

                // Формирование URL запроса с закодированным путем к создаваемой папке
                var encodedPath = Uri.EscapeDataString(folderPath);
                var url = $"https://cloud-api.yandex.net/v1/disk/resources?path={encodedPath}";

                // Создание объекта HttpClient
                using (var httpClient = new HttpClient())
                {
                    // Установка заголовка авторизации
                    httpClient.DefaultRequestHeaders.Add("Authorization", $"OAuth {_key}");

                    // Отправка запроса методом PUT
                    var response = await httpClient.PutAsync(url, null);

                    // Проверка статуса ответа
                    response.EnsureSuccessStatusCode();
                }
                //Выгрузка инфы в БД
                UploadFolderDB(folderName, "", _path);

                string helpPath = "/" + folderName;
                if (_path.EndsWith(helpPath))
                {
                    _path = _path.Substring(0, _path.Length - helpPath.Length);
                }
                return RedirectToAction(nameof(OpenFolder), new { folderName });
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Возникла ошибка при создании папки: {ex.Message}");
            }
        }

        protected void UploadFolderDB(string folderName, string folderDescription, string folderWay)
        {
            var newFolder = new Models.Folder
            {
                FolderName = folderName,
                FolderWay = folderWay,
                FolderDescription = folderDescription,
                CreationDate = DateTime.Now
            };
            _context.Folders.Add(newFolder);
            _context.SaveChanges();
            return;
        }


        [HttpPost]
        public async Task<IActionResult> DownloadFile(int fileId)
        {
            try
            {
                var api = new DiskHttpApi(_key);

                // загрузка файла на компьютер

                string filename = _context.Files
                    .Where(d => d.FileId == fileId)
                    .Select(s => s.FileName)
                    .FirstOrDefault();

                // Скачиваем файл и сохраняем его по указанному пути
                await api.Files.DownloadFileAsync(_path + "/" + filename, filename);
                string folderName = _context.Folders
                    .Where(f => f.FolderId == _actualFolderId)
                    .Select(s => s.FolderName)
                    .FirstOrDefault();
                string helpPath = "/" + folderName;
                if (_path.EndsWith(helpPath))
                {
                    _path = _path.Substring(0, _path.Length - helpPath.Length);
                }
                return RedirectToAction(nameof(OpenFolder), new { folderName });
            }

DriveSec/Views/DriveSec/Index.cshtml
@model (List<DriveSec.Models.File> Files, List<DriveSec.Models.Folder> Folders)


@{
    ViewData["Title"] = "Home Page";
}

<section class="mt-3">
    @* @if (ViewData["SuccessMessage"] != null)
    {
        <p class="text-success">@ViewData["SuccessMessage"]</p>
    }
    @if (ViewData["SuccessMessage"] != null)
    {
        <p class="text-danger">@ViewData["ErrorMessage"]</p>
    } *@

    <div class="container px-0 ms-4">
        <h1 class="text-white text-left" style="font-size: 32px; font-weight: 600;">
            Файлы
        </h1>
    </div>

</section>

<section class="file-container d-flex flex-wrap gap-3">
    @foreach (var folder in Model.Folders)
    {
        <div class="file-item d-flex flex-column align-items-center" style="margin-top: -20px; ">
            <svg width="175" height="175" viewBox="0 0 175 175" fill="none" xmlns="http://www.w3.org/2000/svg">
                <a href="@Url.Action("OpenFolder", "DriveSec", new { folderName = folder.FolderName })">
                <path d="M21.875 58.3333H148.325C150.005 58.3333 150.845 58.3333 151.487 58.6603C152.051 58.9479 152.51 59.4069 152.798 59.9714C153.125 60.6131 153.125 61.4532 153.125 63.1333V133.742C153.125 135.422 153.125 136.262 152.798 136.904C152.51 137.468 152.051 137.927 151.487 138.215C150.845 138.542 150.005 138.542 148.325 138.542H26.675C24.9948 138.542 24.1548 138.542 23.513 138.215C22.9485 137.927 22.4896 137.468 22.202 136.904C21.875 136.262 21.875 135.422 21.875 133.742V58.3333Z"
                    fill="white" />
                <path d="M21.875 40.4583C21.875 38.5727 21.875 37.6299 22.4608 37.0441C23.0466 36.4583 23.9894 36.4583 25.875 36.4583H71.2598C72.0773 36.4583 72.4861 36.4583 72.8536 36.6106C73.2212 36.7628 73.5102 37.0518 74.0882 37.6299L94.7917 58.3333H21.875V40.4583Z"
                    fill="white" />
                </a>
            </svg>
            <div class="d-flex flex-md-row" style="margin-top: -20px; max-width: 200px">
                <p class="FName">@folder.FolderName</p>
                <button type="button" class="tgle_menu btn btn-light btn-sm dropdown-toggle dropdown-toggle-split ms-2"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    <span class="visually-hidden"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <form method="post" asp-action="DeleteFolder" asp-controller="DriveSec" onsubmit="showImageModal(event)">
                            <input type="hidden" name="folderId" value="@folder.FolderId" />
                            <button type="submit" class="dropdown-item">Удалить</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    }
    @foreach (var file in Model.Files)
    {
        <div class="file-item d-flex flex-column align-items-center" style="margin-top: 10px; ">
            <svg width="120" height="120" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd"
                      d="M64 10V43L64 43.0544C63.9999 43.4785 63.9998 43.8906 64.0455 44.2305C64.097 44.6137 64.2226 45.051 64.5858 45.4142C64.949 45.7774 65.3863 45.903 65.7695 45.9545C66.1094 46.0002 66.5215 46.0001 66.9456 46L67 46H100V80C100 94.1421 100 101.213 95.6066 105.607C91.2132 110 84.1421 110 70 110H50C35.8579 110 28.7868 110 24.3934 105.607C20 101.213 20 94.1421 20 80V40C20 25.8579 20 18.7868 24.3934 14.3934C28.7868 10 35.8579 10 50 10H64ZM66 10V43C66 43.4997 66.0021 43.7738 66.0277 43.964L66.0287 43.9713L66.036 43.9723C66.2262 43.9979 66.5003 44 67 44H100V43.2843C100 39.1968 100 37.153 99.2388 35.3153C98.4776 33.4776 97.0325 32.0325 94.1422 29.1422L94.1421 29.1421L80.8579 15.8579C77.9676 12.9676 76.5224 11.5224 74.6847 10.7612C72.847 10 70.8032 10 66.7157 10H66Z"
                      fill="white" />
            </svg>

            <div class="d-flex flex-md-row" style="margin-top: 5px; max-width: 145px">
                <p class="FName">@file.FileName</p>
                <button type="button"
                        class="tgle_menu btn btn-light btn-sm dropdown-toggle dropdown-toggle-split ms-2"
                        data-bs-toggle="dropdown" aria-expanded="false"
                        style="height: 20px; width: 30px; margin-top: 7px; padding-top: 0px;">
                    <span class="visually-hidden"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <form method="post" asp-action="DownloadFile" asp-controller="DriveSec" onsubmit="showImageModal(event)">
                            <input type="hidden" name="fileId" value="@file.FileId" />
                            <button type="submit" class="dropdown-item">Скачать</button>
                        </form>
                    </li>
                    <li>
                        <form method="post" asp-action="DeleteFile" asp-controller="DriveSec" onsubmit="showImageModal(event)">
                            <input type="hidden" name="fileId" value="@file.FileId" />
                            <button type="submit" class="dropdown-item">Удалить</button>
                        </form>
                    </li>
                </ul>

            </div>
        </div>
    }
</section>

<!-- Модальное окно QR -->
<div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <img src="~/QR.png" class="img-fluid" alt="Загрузка...">
            </div>
        </div>
    </div>
</div>
<!-- Модальное окно QR -->


<script>
    function showImageModal(event) {
        event.preventDefault();

        var imageModal = new bootstrap.Modal(document.getElementById('imageModal'));
        imageModal.show();

        setTimeout(function () {
            imageModal.hide();
            event.target.submit();
        }, 5000);
    }
</script>